services:
  postgres-db:
    image: postgres:15-alpine
    container_name: intercom-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - intercom-network

networks:
  intercom-network:
    driver: bridge