server:
  port: 8090

spring:
  application:
    name: smart-virtual-intercom

  datasource:
    url: jdbc:postgresql://localhost:5433/${DB_NAME:intercom_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:SecretPassword2026}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

resilience4j.ratelimiter:
  instances:
    gateRateLimiter:
      limitForPeriod: 3
      limitRefreshPeriod: 1m
      timeoutDuration: 0s