package com.alex.intercom.adapters.persistence;

import com.alex.intercom.adapters.persistence.entities.CallLogEntity;
import com.alex.intercom.adapters.persistence.repositories.JpaCallLogRepository;
import com.alex.intercom.domain.CallLog;
import com.alex.intercom.ports.out.CallLogRepositoryPort;
import org.springframework.stereotype.Component;

import java.util.List;
import java.util.stream.Collectors;

/**
 * Persistence Adapter implementing the outbound port for call logs history.
 */
@Component
public class CallLogPersistenceAdapter implements CallLogRepositoryPort {

    private final JpaCallLogRepository repository;

    public CallLogPersistenceAdapter(JpaCallLogRepository repository) {
        this.repository = repository;
    }

    @Override
    public CallLog save(CallLog domainModel) {
        CallLogEntity entity = new CallLogEntity(
                null, // Autogenerated by PostgreSQL sequence
                domainModel.getSessionId(),
                domainModel.getStartTime(),
                domainModel.getEndTime(),
                domainModel.getTerminationReason(),
                domainModel.getGuestIp()
        );

        CallLogEntity savedEntity = repository.save(entity);

        return new CallLog(
                savedEntity.getId(),
                savedEntity.getSessionId(),
                savedEntity.getStartTime(),
                savedEntity.getEndTime(),
                savedEntity.getTerminationReason(),
                savedEntity.getGuestIp()
        );
    }

    @Override
    public List<CallLog> findAll() {
        return repository.findAll().stream()
                .map(entity -> new CallLog(
                        entity.getId(),
                        entity.getSessionId(),
                        entity.getStartTime(),
                        entity.getEndTime(),
                        entity.getTerminationReason(),
                        entity.getGuestIp()
                ))
                .collect(Collectors.toList());
    }
}